[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "EmptySpaceSearch"
version = "0.5.1"
authors = [
    {name = "Mário Antunes", email = "mario.antunes@ua.pt"}
]
description = "Empty Space Search"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.0.0",
    "torann>=0.2.1",
]

[project.urls]
Homepage = "https://github.com/mariolpantunes/ess"
Documentation = "https://mariolpantunes.github.io/ess/"
Repository = "https://github.com/mariolpantunes/ess"
Issues = "https://github.com/mariolpantunes/ess/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 120

[tool.basedpyright]
typeCheckingMode = "standard"
include = ["src/ess"]
reportImportCycles = "none"

[tool.vulture]
paths = ["src/ess"]
min_confidence = 80
