name: Generate and Deploy Docs

on:
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc matplotlib numpy faiss-cpu
          pip install .

      - name: Generate Docs
        run: |
          pdoc --math -d google -o docs_build src/ess --logo "assets/ess_logo.svg" --favicon "assets/ess_logo.svg"
          cp -r assets docs_build/assets

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs_build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
